# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Dependencies list in Cargo.{toml,lock}.
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    # Transitive dependencies that violate our MSRV.
    ignore:
      # MSRV(1.65)
      - dependency-name: "textwrap"
        versions: [ ">=0.16.2" ]
      # MSRV(1.65)
      - dependency-name: "once_cell"
        versions: [ ">=1.21.0" ]
  # Dependencies listed in .github/workflows/*.yml
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Dependencies listed in e2e-tests/cmd/go/go.{mod,sum}.
  # NOTE: We do not auto-bump go-pathrs or examples/go because we want to
  # continue to support Go 1.18 for as long as reasonable.
  - package-ecosystem: "gomod"
    directory: "/e2e-tests/cmd/go"
    schedule:
      interval: "daily"
